
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install -y mysql-client
      - run: sudo composer self-update
      - run: sudo composer update
      - run: sudo npm update
      - run: php artisan migrate --env=testing --database='mysql2' --force
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
