version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      - run:
         name: Install nvm
         command: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

      - run:
         name: Download NodeJS
         command: nvm install node
         command: export NVM_DIR="$HOME/.nvm"
         command: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
         
      - run:
         name: Install PHP mysql
         command: sudo apt-get install -y mysql-client mysql-server

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.testing .env

      - run:
         name: Update composer to latest version
         command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NodeJS Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      #- run:
      #   name: Migrate Laravel Database
      #   command: php artisan migrate --env=testing --force

      - run:
         name: Compile Javascript & CSS for Browser Testing
         command: npm run production

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: vendor/bin/phpunit
