version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/master

    steps:
      - checkout
      - run: git config --global user.name "$GIT_USERNAME" && git config --global user.email "$GIT_EMAIL"
      - run: cd .. && git clone "$CIRCLE_REPOSITORY_URL" gh-pages && cd gh-pages && git checkout gh-pages && rm -r *
      - run: sudo npm install apidoc -g
      - run: cd .. && apidoc -i master -o gh-pages
      - run: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd ../gh-pages && git add -A && git commit -m "Update API documentation" || true && git push https://$GH_TOKEN@github.com/RoboJackets/apiary gh-pages || true
            fi
